fetchDownloadXLSX
    ✕ should download XLSX successfully (8 ms)
    ✕ should handle download error (53 ms)

  ● fetchDownloadXLSX › should download XLSX successfully

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

      54 |     expect(document.createElement).toHaveBeenCalledWith('a');
      55 |     expect(URL.createObjectURL).toHaveBeenCalled();
    > 56 |     expect(URL.revokeObjectURL).toHaveBeenCalled();
         |                                 ^
      57 |   });
      58 |  
      59 |   it('should handle download error', async () => {

      at _callee$ (src/services/http/downloadXlsx.test.js:56:33)
      at tryCatch (src/services/http/downloadXlsx.test.js:2:1)
      at Generator.<anonymous> (src/services/http/downloadXlsx.test.js:2:1)
      at Generator.next (src/services/http/downloadXlsx.test.js:2:1)
      at asyncGeneratorStep (src/services/http/downloadXlsx.test.js:2:1)
      at _next (src/services/http/downloadXlsx.test.js:2:1)

  ● fetchDownloadXLSX › should handle download error

    expect(received).toHaveBeenCalledWith(...expected)

    Matcher error: received value must be a mock or spy function

    Received has type:  function
    Received has value: [Function log]

      73 |       content: 'Network error',
      74 |     });
    > 75 |     expect(console.log).toHaveBeenCalledWith('Network error', 'failed to download xlsx');
         |                         ^
      76 |   });
      77 | });

      at _callee2$ (src/services/http/downloadXlsx.test.js:75:25)
      at tryCatch (src/services/http/downloadXlsx.test.js:2:1)
      at Generator.<anonymous> (src/services/http/downloadXlsx.test.js:2:1)
      at Generator.next (src/services/http/downloadXlsx.test.js:2:1)
      at asyncGeneratorStep (src/services/http/downloadXlsx.test.js:2:1)
      at _next (src/services/http/downloadXlsx.test.js:2:1)

  console.log
    Network error failed to download xlsx

      at _callee$ (src/services/http/downloadXlsx.js:32:15)
